
<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->

<!-- Use templates folder to update -->


<main>
    <meta name="theme-color" content="currentcolor">


{#if !loaded}
<Loader height="100vh" width="100vw" position="fixed" bgcolor="rgba(255, 255, 255, 0.7)" /> 
{/if}


<AreaMap bind:draw_type={drwt}/>


<Panel>
    <div class="" style="">
        <h1>Draw Your Own Geography</h1>

        <form onsubmit="return false">
            <button on:click={()=>drwt.set('draw_rectangle')}>Rectangular</button>
            <button on:click={()=>$drwt='draw_circle'}>Radius</button>
            <button on:click={()=>$drwt='draw_polygon'}>Custom Polygon</button>
        </form>
        
        </div>
       
    </Panel>
</main>


<script>
    
import { onMount } from "svelte";
import {default as AreaMap} from './AreaMap.svelte';
import Loader from './Loader.svelte';

import Panel from './Panel.svelte';
// import AreaMap ,{ draw_type } from ".s/AreaMap";

let loaded=false

let drwt;

async function init(){

    loaded = true;
	console.log($drwt,AreaMap)
	$drwt = 'draw_circle'


}


// draw_type.set('draw_radius')



{/* <Map bind:map={map} style={mapstyle} minzoom={4} maxzoom={14} bind:zoom={mapZoom}>
	<MapSource id="oa" type="vector" url={vector.url} layer={vector.layer} promoteId={vector.id} minzoom={8} >
		{#if poplookup}
		<MapLayer
		  id="oa_fill"
			source="oa"
			sourceLayer={vector.layer}
			type="fill"
			click={true}
			hover={true}
			selected={codes['2011']}
			bind:drawing={drawing}
			on:click={clickSelect}
			{hovered}
			paint="{{
			'fill-color': ['case',
				['==', ['feature-state','selected'], true], 'rgba(0, 0, 0, 0.2)',
				'rgba(0, 0, 0, 0)'
			],
		}}" order="boundary_state" />
		{/if}
		<MapLayer id="oa_boundary" source="oa" sourceLayer={vector.layer} type="line" paint="{{
			'line-color': ['case',
				['==', ['feature-state','hovered'], true], 'rgb(0, 0, 0)',
				'rgb(128, 128, 128)'
			],
			'line-width': ['case',
				['==', ['feature-state','hovered'], true], 1,
				0.25
			],
		}}" order="boundary_country" />
	</MapSource>
	{#if centroids}
	<MapDraw on:draw={drawSelect} bind:draw={draw} bind:polygons={polygons} bind:drawing={drawing} bind:loaded={loaded} {centroids}/>
	{/if}
	{#if centroids}
	<MapSource id="centroids" type="geojson" data={centroids} promoteId="id">
		<MapLayer
		  id="centroids11"
			source="centroids"
			type="circle"
			filter={["==", "c11", true]}
			paint="{{
			'circle-color':  'rgba(0,0,0,0.5)',
			'circle-radius': [
				"interpolate", ["linear"], ["zoom"],
				9, 0.3, 14, 2
			]
		}}" minzoom={8} />
		<MapLayer
		  id="centroids01"
			source="centroids"
			type="circle"
			filter={[
				"all",
				["==", "c01", true],
				["==", "c11", false]
			]}
			paint="{{
			'circle-color':  'rgba(255,0,0,0.5)',
			'circle-radius': [
				"interpolate", ["linear"], ["zoom"],
				9, 0.3, 14, 2
			]
		}}" minzoom={8} />
	</MapSource> */}







onMount(init);

</script>


<style>
    :global(body) {
    margin: 0;
    padding: 0;
}

:global(.mapboxgl-map){
  width:100%;
  height:100%;
}

:global(main){
  font-size-adjust:.10;
  font-size:10px;
}

</style>
